# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([( name: 'Chicago' ), ( name: 'Copenhagen' )])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Post.create(title: "Youtube comments were the worst comments in the world, anyway.", link: "http://www.reddit.com/r/AdviceAnimals/comments/1q4oqr/youtube_comments_were_the_worst_comments_in_the/", author: "Empanser")
Post.create(title: "Webster was quarantined with ringworm.. Nugget broke him out", link: "http://www.reddit.com/r/aww/comments/1q4oql/webster_was_quarantined_with_ringworm_nugget/", author: "Reeeecola")
Post.create(title: "I can't help but believe that there is only one genuinly friendly subreddit in this entire community. (inb4 all ur postz suxors my nutsors)", link: "http://www.reddit.com/r/AdviceAnimals/comments/1q4onz/i_cant_help_but_believe_that_there_is_only_one/", author: "cjaredrun")
Post.create(title: "My friend didn't take homecoming very seriously.", link: "http://www.reddit.com/r/funny/comments/1q4ou0/my_friend_didnt_take_homecoming_very_seriously/", author: "pwill49")
Post.create(title: "Well It's 4:30pm on my day off today", link: "http://www.reddit.com/r/AdviceAnimals/comments/1q4oua/well_its_430pm_on_my_day_off_today/", author: "suttert")
Post.create(title: "Reddit, what's your favorite euphemism that you wished more people knew?", link: "http://www.reddit.com/r/AskReddit/comments/1q4orf/reddit_whats_your_favorite_euphemism_that_you/", author: "mironp")
Post.create(title: "'Star Wars: Episode VII': Release set for December 18, 2015", link: "http://www.reddit.com/r/movies/comments/1q4om8/star_wars_episode_vii_release_set_for_december_18/", author: "misterAction")
Post.create(title: "The sugar walls just feel so much better", link: "http://www.reddit.com/r/AdviceAnimals/comments/1q4oqy/the_sugar_walls_just_feel_so_much_better/", author: "reduceandreuse")
Post.create(title: "Tasmanian devil babies are soft cuties! :D", link: "http://www.reddit.com/r/aww/comments/1q4ooe/tasmanian_devil_babies_are_soft_cuties_d/", author: "pencil_pine")
Post.create(title: "Bo Diddley - Somewhere", link: "http://www.reddit.com/r/Music/comments/1q4olc/bo_diddley_somewhere/", author: "Sulungskwa")
Post.create(title: "The ultimate battle!", link: "http://www.reddit.com/r/funny/comments/1q49ib/the_ultimate_battle/", author: "arkandji")
Post.create(title: "Links between The Hobbit & The Lord of the Rings", link: "http://www.reddit.com/r/movies/comments/1q41g1/links_between_the_hobbit_the_lord_of_the_rings/", author: "MakeMeASteak")
Post.create(title: "Since starting my new job", link: "http://www.reddit.com/r/gifs/comments/1q3yin/since_starting_my_new_job/", author: "im_a_middle_child")
Post.create(title: "This guy saved my ass. Thanks, Grant.", link: "http://www.reddit.com/r/AdviceAnimals/comments/1q3xvx/this_guy_saved_my_ass_thanks_grant/", author: "ducksizedhorses")
Post.create(title: "XBox One Official Watchdog trailer is PS4 Footage", link: "http://www.reddit.com/r/gaming/comments/1q3xw3/xbox_one_official_watchdog_trailer_is_ps4_footage/", author: "Fixn")
Post.create(title: "Aircraft Carrier's wake", link: "http://www.reddit.com/r/pics/comments/1q3s6w/aircraft_carriers_wake/", author: "ErrorlessGnome")
Post.create(title: "Remember that guy with the 1820 pound pet buffalo? He lives down the road from my in laws. Here he is taking him for a car ride.", link: "http://www.reddit.com/r/WTF/comments/1q3ns9/remember_that_guy_with_the_1820_pound_pet_buffalo/", author: "Chuknorris86")
Post.create(title: "EU rules that gay Africans are entitled to asylum - According to the European Court of Justice, a gay refugee from a country where people are jailed for being homosexual does qualify as a persecuted group eligible for asylum.", link: "http://www.reddit.com/r/worldnews/comments/1q3moz/eu_rules_that_gay_africans_are_entitled_to_asylum/", author: "rstevens94")
Post.create(title: "TIL there are molds growing inside the Chernobyl Nuclear Plant that "feed" on gamma radiation", link: "http://www.reddit.com/r/todayilearned/comments/1q3mtc/til_there_are_molds_growing_inside_the_chernobyl/", author: "preacher37")
Post.create(title: "University physicists study urine splash-back and offer best tactics for men", link: "http://www.reddit.com/r/science/comments/1q3mwg/university_physicists_study_urine_splashback_and/", author: "petskup")
Post.create(title: "Did you just hear that?", link: "http://www.reddit.com/r/aww/comments/1q3jz6/did_you_just_hear_that/", author: "mrflaco75")
Post.create(title: "/u/Kristler helps a high school student to think like a programmer instead of doing his homework for him", link: "http://www.reddit.com/r/bestof/comments/1q3r8p/ukristler_helps_a_high_school_student_to_think/", author: "qoumran")
Post.create(title: "Marvel and Netflix Join Forces to Develop Historic Four Series Epic plus a Mini-Series Event", link: "http://www.reddit.com/r/television/comments/1q3ods/marvel_and_netflix_join_forces_to_develop/", author: "TajtheDestroyer")
Post.create(title: "The CIA is paying AT&T $10 Million a year for access to call data.", link: "http://www.reddit.com/r/news/comments/1q3fe6/the_cia_is_paying_att_10_million_a_year_for/", author: "Ed_Alchemist")
Post.create(title: "The Internet Archive seeks donations after fire destroys $600,000 of equipment", link: "http://www.reddit.com/r/technology/comments/1q3dyk/the_internet_archive_seeks_donations_after_fire/", author: "nastratin")
Post.create(title: "We are John Sayles (director) and Edward James Olmos (actor) from GO FOR SISTERS - Ask us whatever you want.", link: "http://www.reddit.com/r/IAmA/comments/1q40fp/we_are_john_sayles_director_and_edward_james/", author: "JohnSayles")
Post.create(title: "Men Without Hats - The Safety Dance", link: "http://www.reddit.com/r/Music/comments/1q3nbz/men_without_hats_the_safety_dance/", author: "ShevyPri")
Post.create(title: "The note Albert Camus sent to his teacher shortly after receiving the Nobel Prize for Literature.", link: "http://www.reddit.com/r/books/comments/1q3l9u/the_note_albert_camus_sent_to_his_teacher_shortly/", author: "reidhoch")
Post.create(title: "Could a larger black hole absorb a smaller black hole? What would happen?", link: "http://www.reddit.com/r/askscience/comments/1q3mer/could_a_larger_black_hole_absorb_a_smaller_black/", author: "owlpole")
Post.create(title: "What is something that you prefer the cheaper version of?", link: "http://www.reddit.com/r/AskReddit/comments/1q3p5j/what_is_something_that_you_prefer_the_cheaper/", author: "jpruitt4")
Post.create(title: "Chamonix Mont Blanc, France [1920x1200]", link: "http://www.reddit.com/r/EarthPorn/comments/1q3m25/chamonix_mont_blanc_france_1920x1200/", author: "SKhan13")
Post.create(title: "ELI5: The difference between lagers, stouts, ales, porters, etc.", link: "http://www.reddit.com/r/explainlikeimfive/comments/1q2urh/eli5_the_difference_between_lagers_stouts_ales/", author: "HeyYoPaul")
Post.create(title: "I miss my phone.", link: "http://www.reddit.com/r/pics/comments/1q3tfu/i_miss_my_phone/", author: "Siriacus")
Post.create(title: "Moonrise in Alaska [1235 x 832]", link: "http://www.reddit.com/r/EarthPorn/comments/1q3opk/moonrise_in_alaska_1235_x_832/", author: "danrennt98")
Post.create(title: "We.... We wait until she sleeps. And then.... We make her cuter.", link: "http://www.reddit.com/r/aww/comments/1q3lft/we_we_wait_until_she_sleeps_and_then_we_make_her/", author: "brandycute1")